version: '3.2'
services:
  spark:
    image: "spark:latest"
    ports:
    - "8080:8080"
    - "7077:7077"
    - "7072:7072"
    - "8081:8081"
    - "8082:8082"
    - "5050:5050"
    - "5051:5051"
    - "4040:4040"
    - "9001:9001"
    volumes:
    - ../data/spark:/usr/local/supervisor
    - ../data/spark/logs:/usr/local/supervisor/logs
    networks:
      - default
    entrypoint: /etc/entrypoint.sh
networks:
  default:
    external:
      name: dockernet
