version: '3.2'
services:
  zeppelin:
    image: "nifi:latest"
    ports:
    - "8080:8080"
    volumes:
    - ../data/nifi/data:/usr/nifi/data
    networks:
      - default
networks:
  default:
    external:
      name: dockernet
