version: '3.2'
services:
  zeppelin:
    image: "nifi:latest"
    ports:
    - "8080:8080"
    volumes:
    - ../data/nifi/data:/usr/nifi/data
    networks:
    - default
  postgres:
    image: "postgres:latest"
    ports:
    - "5432:5432"
    networks:
    - default
networks:
  default:
    external:
      name: dockernet
