version: '3.2'
services:
  nifi:
    image: "nifi:latest"
    ports:
    - "8080:8080"
    volumes:
    - ../data/nifi/drivers:/usr/nifi-1.2.0/drivers
    - ../data/nifi/conf:/usr/nifi-1.2.0/conf
    # - ../data/nifi/work:/usr/nifi-1.2.0/work
    - ../data/nifi/run:/usr/nifi-1.2.0/run
    - ../data/nifi/state:/usr/nifi-1.2.0/state
    - ../data/nifi/content_repository:/usr/nifi-1.2.0/content_repository
    - ../data/nifi/database_repository:/usr/nifi-1.2.0/database_repository
    - ../data/nifi/flowfile_repository:/usr/nifi-1.2.0/flowfile_repository
    - ../data/nifi/provenance_repository:/usr/nifi-1.2.0/provenance_repository
    environment:
    - NIFIVER=1.2.0
    entrypoint:
    - /usr/nifi-1.2.0/bin/nifi.sh
    - run
    networks:
    - default
  postgres:
    image: "postgres:latest"
    environment:
    - POSTGRES_PASSWORD=ppass
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ../data/postgres/pgdata:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
    networks:
    - default
  mongo:
    image: "mongo:latest"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=madmin
    - MONGO_INITDB_ROOT_PASSWORD=mpass
    volumes:
    - ../data/mongo:/data/db
    ports:
    - "27017:27017"
    - "28017:28017"
    networks:
    - default
    command: mongod
  mongoclient:
    image: "mongoclient/mongoclient:latest"
    volumes:
    - ../data/mongoclient:/data/db
    ports:
    - "3000:3000"
    networks:
    - default
networks:
  default:
    external:
      name: dockernet
