version: '3.2'
services:
  cloudera:
    image: cloudera/quickstart:latest
    command: /usr/bin/docker-quickstart
    privileged: true
    hostname: quickstart.cloudera
    tty: true
    ports:
      - "8020:8020"
      - "8022:22"     # ssh
      - "7180:7180"   # Cloudera Manager
      - "8888:8888"   # HUE
      - "11000:11000" # Oozie
      - "50070:50070" # HDFS REST Namenode
      - "2181:2181"
      - "11443:11443"
      - "9090:9090"
      - "8088:8088"
      - "19888:19888"
      - "9092:9092"
      - "8983:8983"
      - "16000:16000"
      - "16001:16001"
      - "42222:22"
      - "8042:8042"
      - "60010:60010"
      - "8080:8080"
      - "7077:7077"
    networks:
    - default
  # postgres:
  #   image: "postgres:latest"
  #   environment:
  #   - POSTGRES_PASSWORD=ppass
  #   - PGDATA=/var/lib/postgresql/data/pgdata
  #   volumes:
  #   - ../data/postgres/pgdata:/var/lib/postgresql/data/pgdata
  #   ports:
  #   - "5432:5432"
  #   networks:
  #   - default
networks:
  default:
    external:
      name: dockernet
