version: '3.2'
services:
  zeppelin:
    image: "zeppelin:latest"
    ports:
    - "8080:8080"
    volumes:
    - ../data/zeppelin/notebook:/usr/zeppelin/notebook
    - ../data/zeppelin/data:/usr/zeppelin/data
